### PR TITLE
De-Identification fixes

### PR DESCRIPTION
**Pull request by lmperry**
1. 0bd0b5b IMO, and my use case, when the `--de_identify` option is used we don't want the `PatientID` used for the subject_code as it sometimes contains SSNs 😱  
2. b9dfcd4 The arg_parser arg for `--de-identify` was not working, as it was referenced in the code as `de_identify`. Others fixed as well. 
3. 3c9ecd3 These fields were not being removed using `dcm.pop`. I didn't investigate further since setting them to empty strings suited my use case.

### CODE REVIEW

**Comment by gsfr** [comment]
Thanks, @lmperry. Taking the liberty to add a commit here. Let me know what you think.

`argparse` translates dashes to underscores, so reverting those changes.

Good point on not using the `PatientID` when de-identifying.

`dcm.pop()` does indeed not work. Good catch. Reverting back to original (ugly) `del` statements.

Also, fixing pylint errors and pinning all dependencies.

**Comment by lmperry** [comment]
@gsfr tested your changes aaaand...  all good.  I added one more small change: text to assuage fears of de-identification not happening.

**Comment by gsfr** [comment]
Sorry, but one more round. @lmperry, good to go?

**Comment by lmperry** [comment]
Much better. I shall remember that.

GTG!

**Pull request merged**
