### PR TITLE
Folder reaper

### PR DESCRIPTION
**Pull request by gsfr**
First pass at folder reaper. The type list still needs to go to a separate json file.

This can be tested against scitran/testdata#reaping.

@mrDarcyMurphy: Is the included types list acceptable to you to facilitate proper file viewing in the UI?

@ryansanford: Please give this a shot and integrate it into the fly/fly infra.

Enables scitran/core#185.

### CODE REVIEW

**Comment by ryansanford** [comment]
@gsfr I bootstrapped my own data. Nice work!!!

A couple issues while playing with this by hand on OSX without docker...
1. The colon character is not supported on HFS filesystem. Suggest changing scitran/testdata to remove the colons. Date labels are still ISO 8601 compliant.
2. Hidden files aren't ignored. In my case, `.DS_Store` files were causing errors like "CRITICAL Files not allowed at group level".

Usability Suggestion:
- Print out all parameters as they have been interpreted, useful for debugging.

Random thought:
Thoughts on supporting structured/unstructured metadata at the Session and/or acquisition level via a special file in the relevant folder. I'm thinking this would help for setting up and sharing scenarios for "search" development and testing.

I think I need a better understanding of how we intend to use setuptools to have an opinion on the below warning. More details on the vision are welcome.

```
C02QJ43DFVH5:reaper ryansanford$ python setup.py develop
/usr/local/lib/python2.7/site-packages/setuptools/dist.py:293: UserWarning: The version specified ('bali.2.0') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  "details." % self.metadata.version
running develop
```

**Comment by ryansanford** [comment]
@gsfr 
I added a schema to the README.md for this PR. Feel free to correct, and/or create something more structured.

**Comment by mrDarcyMurphy** [comment]
@gsfr Initial list looks like a good start. 
- Are the checks case insensitive? For example, the occasional `.JPEG` will show up.
- Perhaps add `.json` to the source code list?

**Comment by gsfr** [comment]
@mrDarcyMurphy: Case insensitiveness added. Good point. Will add json type later.

@ryansanford: Now properly ignoring hidden files. Please re-test.

**Comment by gsfr** [comment]
> Usability Suggestion:
> 
> Print out all parameters as they have been interpreted, useful for debugging.

Done.

> Random thought:
> Thoughts on supporting structured/unstructured metadata at the Session and/or acquisition level via a special file in the relevant folder. I'm thinking this would help for setting up and sharing scenarios for "search" development and testing.

Yes, absolutely. Feel free to file a separate ticket.

> I think I need a better understanding of how we intend to use setuptools to have an opinion on the below warning. More details on the vision are welcome.
> 
> C02QJ43DFVH5:reaper ryansanford$ python setup.py develop
> /usr/local/lib/python2.7/site-packages/setuptools/dist.py:293: UserWarning: The version specified ('bali.2.0') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
>   "details." % self.metadata.version
> running develop

I also saw the warning, but didn't think too much of it. Moving to canonical semver is easy enough, if needed.

**Comment by ryansanford** [comment]
@gsfr 
Commit 0d9f6cb broke the pip install method for me, types.json isn't getting installed.

```
+ folder_reaper --insecure --secret change-me https://flywheel-nginx:443/api /var/scitran/data/testdata/download
Traceback (most recent call last):
  File "/usr/local/bin/folder_reaper", line 5, in <module>
    import reaper.folder_reaper
  File "/usr/local/lib/python2.7/dist-packages/reaper/folder_reaper.py", line 24, in <module>
    with open(os.path.join(os.path.dirname(__file__), 'types.json')) as fd:
IOError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/reaper/types.json'

$ ls -al /usr/local/lib/python2.7/dist-packages/reaper
total 172
drwxr-sr-x   2 root staff  4096 Mar  9 13:29 .
drwxrwsr-x 110 root staff  4096 Mar  9 13:29 ..
-rw-r--r--   1 root staff     0 Mar  9 13:29 __init__.py
-rw-r--r--   1 root staff   144 Mar  9 13:29 __init__.pyc
-rw-r--r--   1 root staff  3747 Mar  9 13:29 dicom_file_reaper.py
-rw-r--r--   1 root staff  4459 Mar  9 13:29 dicom_file_reaper.pyc
-rw-r--r--   1 root staff 11962 Mar  9 13:29 dicom_net_reaper.py
-rw-r--r--   1 root staff 12292 Mar  9 13:29 dicom_net_reaper.pyc
-rw-r--r--   1 root staff  8018 Mar  9 13:29 folder_reaper.py
-rw-r--r--   1 root staff  7275 Mar  9 13:29 folder_reaper.pyc
-rw-r--r--   1 root staff  2834 Mar  9 13:29 gephysio.py
-rw-r--r--   1 root staff  3039 Mar  9 13:29 gephysio.pyc
-rw-r--r--   1 root staff  3621 Mar  9 13:29 meeg_file_reaper.py
-rw-r--r--   1 root staff  4309 Mar  9 13:29 meeg_file_reaper.pyc
-rw-r--r--   1 root staff  5587 Mar  9 13:29 pfile_reaper.py
-rw-r--r--   1 root staff  5896 Mar  9 13:29 pfile_reaper.pyc
-rw-r--r--   1 root staff 16423 Mar  9 13:29 reaper.py
-rw-r--r--   1 root staff 15610 Mar  9 13:29 reaper.pyc
-rw-r--r--   1 root staff  5646 Mar  9 13:29 scu.py
-rw-r--r--   1 root staff  8159 Mar  9 13:29 scu.pyc
-rw-r--r--   1 root staff  3074 Mar  9 13:29 tempdir.py
-rw-r--r--   1 root staff  3491 Mar  9 13:29 tempdir.pyc
-rw-r--r--   1 root staff  2208 Mar  9 13:29 util.py
-rw-r--r--   1 root staff  3401 Mar  9 13:29 util.pyc

```

**Pull request merged**
