### PR TITLE
Add support for pruning reaped DICOMs

### PR DESCRIPTION
**Pull request by ryansanford**
Requires Orthanc DICOM server 1.0 with REST API.
- Introduces new tool `bin/orthanc_reaper` and includes additional positional parameter specifying the Orthanc REST API URI
- Introduces a set of virtual functions to reaper.py that other sub-classed tools can use as hooks to add functionality at predictable points of the reaper process.
  `before_run()`
  `before_reap()`
  `after_reap_success()`
  `after_reap()`
- Blocks all new stores into Orthanc DICOM server for the series being reaped during the C-MOVE, upload to scitran/core API, and deletion from Orthanc.

This approach breaks if there is more than one reaper or other client enabling/disabling stores on orthanc.

### CODE REVIEW

**Comment by gsfr** [comment]
Btw, this is how I run `pylint` and `pep8` locally.

```
pylint --reports=no reaper && pep8 --max-line-length=150 --ignore=E402 reaper || echo "== ERROR =="
```

**Comment by gsfr** [comment]
I added a few _untested_ commits to match the existing code style a little closer. Would like to get orthanc running myself tomorrow.

A crashed reaper is always liable to leave orthanc in a bad state. Couple of ways to mitigate: do as little as possible while orthanc is locked; use the exit status in calling shell to run a `curl` to re-enable stores.

I don't see how we can practically reject stores for extended periods of time. The current code rejects during move, sort, anonymize, compress, and upload. That can easily be 10 minutes, for real data.

Let's discuss further tomorrow. Also, most of the logs should probably be at the `debug` level.

Nice work. Thanks for getting this going.

**Comment by ryansanford** [comment]
Having an issue with the re-used session object, as connection is being closed by server. I'll look at solutions later today

**Comment by ryansanford** [comment]
It would take a little more experimentation, but we could likely only block stores for the Series UID being reaped.

**Comment by gsfr** [comment]
I was vaguely anticipating this and debating which way I should go with my change. The purpose of the requests session is to reuse an existing http connection and to set common request params. We don't have any common params and if the session reuse does not work, we simply shouldn't use a session. Should I update to `requests.post`, etc.?

**Comment by ryansanford** [comment]
I'll test with `requests.post` across the board, and push if it works. I have time for that now.

**Comment by ryansanford** [comment]
@gsfr 
Assuming CI passes, this should be my final commit. If it passes your muster, please merge. I also updated the PR description to reflect the nature of the final PR.

**Comment by gsfr** [comment]
Code looks good, but I'd like to see this new functionality integrated into our CI tests before we merge.

**Comment by ryansanford** [comment]
Fair enough. I'll download and launch orthanc in `test/test.sh`. I will also embed local testdata into this repo to satisfy #28. Let me know if you have objections.

**Comment by ryansanford** [comment]
@gsfr This PR is again ready for your review. Orthanc testing has been added, using a single series from the already downloaded testdata dataset.

**Comment by gsfr** [comment]
I had hoped to stay out of Travis `sudo` land, but building orthanc without `apt-get` installing the dependencies could be challenging. Given that, why not simply `apt-get install orthanc`? Or can we maybe find a static binary somewhere?

Also, is there a `make install` for orthanc? That would allow us to decouple running orthanc from where it happened to get built.

**Comment by ryansanford** [comment]
I wasn't too bothered by the switch to Travis sudo, since the impact on exec time isn't significant relative to the current test suite after the build is cached.

The only official linux binaries for orthanc are via dist package managers. Most recent ubuntu travis offers is 14.04 for which orthanc version is too old to support the API calls we are using. We could build our own binary? Where would be an appropriate place for scitran to persist that?

There is a `make install` option, but that's not required to fulfill the needs of the integration test, so I skipped it in an effort to limit complexity.

**Comment by ryansanford** [comment]
Thanks for that last mod @gsfr. Based upon our conversation on Friday, I'm merging this now, and tagging master 1.0.2

**Comment by gsfr** [comment]
Victory! 👍

**Pull request merged**
