### PR TITLE
Setuptools compatible structure

### PR DESCRIPTION
**Pull request by rmchamberlain**
Updated with requirements.txt

### CODE REVIEW

**Comment by kofalt** [comment]
LGTM. I'm assuming there's still a good reason to have setup.py even with a requirements file, to hold author metadata & package as an egg or what-not?

Deferring to @gsfr for review

**Comment by rmchamberlain** [comment]
I want it so that it creates the entry point scripts in the system path.

**Comment by gsfr** [comment]
`pip install git+https://github.com/scitran/reaper@setuptools2`
seems to work, but does not install any dependencies.

```
$ virtualenv reaperenv
Running virtualenv with interpreter /usr/bin/python2
New python executable in reaperenv/bin/python2
Also creating executable in reaperenv/bin/python
Installing setuptools, pip...done.

$ source reaperenv/bin/activate
(reaperenv)$ pip install git+https://github.com/scitran/reaper@setuptools2
Downloading/unpacking git+https://github.com/scitran/reaper@setuptools2
  Cloning https://github.com/scitran/reaper (to setuptools2) to /tmp/pip-GOWJRw-build
  Running setup.py (path:/tmp/pip-GOWJRw-build/setup.py) egg_info for package from git+https://github.com/scitran/reaper@setuptools2

Installing collected packages: scitran.reaper
  Running setup.py install for scitran.reaper
    Skipping installation of /home/gsfr/reaperenv/lib/python2.7/site-packages/scitran/__init__.py (namespace package)

    Installing /home/gsfr/reaperenv/lib/python2.7/site-packages/scitran.reaper-0.1-py2.7-nspkg.pth
    Installing pfile_reaper script to /home/gsfr/reaperenv/bin
    Installing dicom_net_reaper script to /home/gsfr/reaperenv/bin
    Installing dicom_file_reaper script to /home/gsfr/reaperenv/bin
Successfully installed scitran.reaper
Cleaning up...

(reaperenv)$ dicom_file_reaper -h
Traceback (most recent call last):
  File "/home/gsfr/reaperenv/bin/dicom_file_reaper", line 9, in <module>
    load_entry_point('scitran.reaper==0.1', 'console_scripts', 'dicom_file_reaper')()
  File "/home/gsfr/reaperenv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 521, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/gsfr/reaperenv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2632, in load_entry_point
    return ep.load()
  File "/home/gsfr/reaperenv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2312, in load
    return self.resolve()
  File "/home/gsfr/reaperenv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2318, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/gsfr/reaperenv/local/lib/python2.7/site-packages/scitran/reaper/dicom_file_reaper.py", line 15, in <module>
    import dicom
ImportError: No module named dicom
```

**Comment by rmchamberlain** [comment]
You have you install with `-r requirements.txt`.

**Comment by gsfr** [comment]
I'm sorry, I really don't seem to know much about python packaging. Now, I can't figure out how to combine the -r option with installing directly from github. This, at least, does not work:
`pip install -r requirements.txt git+https://github.com/scitran/reaper@setuptools2`
Is this maybe a reason for not going with a separate requirements file?

**Comment by rmchamberlain** [comment]
I've never used requirements.txt before, so I'm not sure if you can install
directly from GitHub and install dependencies in one command.  If you close
the repo, you can install the dependencies and reaper with `pip install -r
requirements.txt -e .`

**Comment by kofalt** [comment]
Pinging @andynemzek & @aaltepet for advice about pip. Ref above comments, asking about installing from DVCS and installing dependencies. We had a conversation about this previously for scitran infra so hoping you can help?

**Comment by aaltepet** [comment]
It is possible to install directly from github.  We typically use requirements.txt files, which contain the list of packages to install into a venv.  Optionally, their versions can be pinned.

Each line of requirements.txt can contain whatever follows the 'pip install ...' command.  So, to install from github, it's "pip install -e <git url>".  Note that pip doesn't take a git url verbatim, since it supports more than git it needs more info.  One example is: git+https://github.com/scitran/reaper@setuptools2#egg=scitran.reaper -- this instructs pip to clone the scitran/reaper repository, checkout the setuptools2 branch, and install it as the "scitran.reaper" egg.  It will reside in src/scitran.reaper.  The #egg= part is missing from @gsfr's attempt above.  Putting this in requirements.txt would be this line: "-e git+https://github.com/scitran.reaper@setuptools2#egg=scitran.reaper"

As far as dependencies go, each package should have all dependencies listed in it's setup.py, in install_requires.  If the reaper requires only pydicom in order to run, this would be:

setup(...
  install_requires=['pydicom'],
  ...
)

My approach is, generally, that install_requires contains the package name, and the package is pinned in requirements.txt.  If there are know minimum requirements, you could do 'pydicom>1.0' or something.  Generally I prefer to keep pins in in requirements.txt because it is easier to update dependencies in this single place.  Updating a dependency version when it's pinned in setup.py requires releasing a new egg of that package.

**Comment by gsfr** [comment]
Thanks for the info, @aaltepet. Many things clarified.
Additionally, I was hoping to use `pip` on the command line to install the reaper directly from github, including all the dependencies. Is there any way to achieve that? That is, without first cloning the repo manually.

**Comment by aaltepet** [comment]
Yes, you can use pip on the commandline to install the reaper directly.
You use:
pip install -e <git url>

If you tried that earlier and got a "cannot import dicom" error, it should
be resolved once you add pydicom to install_requires.  I would expect that
doing a pip install -e of the reaper in a fresh virtualenv should pull in
all of reaper's dependencies.

**Comment by gsfr** [comment]
Per offline discussion between @rmchamberlain and myself, we'd be fine with either cloning the repo and then running `pip install -r requirements.txt` or even pointing pip to a remote requirements file.
Medium term goal is to get rid if scitran.data and related dependencies.

**Pull request merged**
