### PR TITLE
Bootstrap

### PR DESCRIPTION
**Pull request by gsfr**
Small functional change in metadata payload in 29db44c. Lightweight stuff, otherwise.

@ryansanford Could you give this a test run please?

### CODE REVIEW

**Comment by ryansanford** [comment]
@gsfr Result with the default test data is success. I'll try some other datasets this afternoon before the standup.

We will need to update scitran/core to make use of this for bootstrapping.

**Comment by ryansanford** [comment]
@gsfr 

Get an error when I have a file without an extension at the root of the acquisition folder. This might not be a regression?

```
C02QJ43DFVH5:reaper ryansanford$ ./bin/folder_uploader --insecure --secret "change-me" 'https://inv-ryan-04.invenshure.com/api' /Users/ryansanford/testdata/junk 
2016-05-17 13:51:54     INFO Inspecting  /Users/ryansanford/testdata/junk
Traceback (most recent call last):
  File "./bin/folder_uploader", line 7, in <module>
    reaper.folder_uploader.main()
  File "/usr/local/lib/python2.7/site-packages/reaper/folder_uploader.py", line 193, in main
    projects = scan_folder(args.path)
  File "/usr/local/lib/python2.7/site-packages/reaper/folder_uploader.py", line 78, in scan_folder
    f['type'] = guess_filetype(f['path'])
  File "/usr/local/lib/python2.7/site-packages/reaper/folder_uploader.py", line 35, in guess_filetype
    return filetype
UnboundLocalError: local variable 'filetype' referenced before assignment
```

**Comment by gsfr** [comment]
@ryansanford Good catch. Not a regression. Fix pushed.

**Comment by ryansanford** [comment]
@gsfr Fix worked for all my limited sets of test data.

**Pull request merged**
