### PR TITLE
Setuptools2

### PR DESCRIPTION
**Pull request by rmchamberlain**
Restructures the directories and adds a setup.py for installation via pip.

### CODE REVIEW

**Comment by gsfr** [comment]
Looks nice. Rather uninvasive.
I'm used to seeing a `requirements.txt` file in these packages. Any thoughts on that?
[Here](https://caremad.io/2013/07/setup-vs-requirement/) is somebody's opinion that seemed reasonable.

**Comment by kofalt** [comment]
Does it make sense to harmonize with the main scitran infra? Whichever is most useful, setup vs requirements, I assume that we should use the same across the board.

**Comment by rmchamberlain** [comment]
I don't have a strong preference either way, so whichever we use elsewhere
is good with me.  What do we use elsewhere?

On Thu, Jul 16, 2015 at 10:45 AM, Nathaniel Kofalt <notifications@github.com

**Comment by kofalt** [comment]
The main scitran infra uses a requirements file.

**Comment by rmchamberlain** [comment]
I've switched to requirements.txt.  I'll cancel this PR and make a new one.

**Pull request closed without merging**
