### PR TITLE
Add Dockerfile and supporting changes

### PR DESCRIPTION
**Pull request by ryansanford**
Intent is that 3rd parties will be able to use the resulting Docker image to execute reaper commands.

Update reaper to allow `opt-in` `opt-out` and `id-field` tags to be outside of `QUERY_TEMPLATE`

Pending requirements before merging:
- [x] @ryansanford to test opt-in option
- [x] @ryansanford to make sure DCMTK license is present as required in resulting docker image.

After merging:
- [ ] Enable dockerhub auto builds on master branch and tags
- [ ] Update setup.py to reflect version specifier `1.0.0` and remove any other version specifiers in code.
- [ ] Push `1.0.0` tag to the above commit
- [ ] Remove all other

### CODE REVIEW

**Comment by gsfr** [comment]
Sorry, this PR got a little bloated by me renaming things to be consistent throughout.

Once CI is green, should we move the Dockerfile to the top level and set up a Docker Hub auto build?

**Comment by ryansanford** [comment]
@gsfr The --opt-in tag is acting like it has a trailing wildcard. Is that intended?

When study has AccessionNumber = flywheel
- `--opt-in AccessionNumber flywhee` causes reaper to pull the study
- `--opt-in AccessionNumber flywheell` causes reaper to ignore the study

If that is expected, we should add that detail to the help text on that parameter.

**Comment by gsfr** [comment]
Yes, that is intended behavior. We currently do a case-insensitive substring search (wildcards on either side). This allows us to have the map key and the opt in key to be the same tag. Agreed that we should document and possibly add a switch to disable this behavior.

**Comment by ryansanford** [comment]
I have confirmed that `make install` on the DCMTK is placing the appropriate COPYRIGHT file at `/usr/local/share/doc/dcmtk/` No changes are required.

**Pull request merged**
