### PR TITLE
Augment types

### PR DESCRIPTION
**Pull request by lmperry**
Include a few more common source code and video formats

### CODE REVIEW

**Comment by lmperry** [comment]
@gsfr I'm using these types for gear outputs. These edits will allow (more than) complete coverage (so far) of the files coming out of those gears.

**Comment by gsfr** [comment]
Thanks, @lmperry.

Couple of things:
- I think the plan is to maintain the types list in [core](https://github.com/scitran/core/blob/961dd4011463dd59e1aa3509e86ce372ae3039d4/api/files.py#L245) and get rid of this one. It is only used by the folder uploader, which would simply stop submitting types and leave that to the core. (Both locations violate my intent to not have instrument-specific terms like dicom or nifti show up in our codebase. Maybe we could think about a synchronous, but external classifier.)
- If you end up editing files.py, please correct the pre-existing typo in the word _spreadsheet_.
- Thoughts on a new _markup_ type for .htm and .html? Might make sense since we don't render those as source, by default.

**Comment by gsfr** [comment]
@nagem Could you please verify my assertion in the first bullet above?

**Comment by lmperry** [comment]
That makes sense. 

I like the cleanliness of having the types defined in an external file (I am actually adding the file to the gear, on build, and using it to classify type). 

_Markup_ type for `html` and `htm` - `web`? `www`? `w3`?

**Comment by gsfr** [comment]
Wanna propose a PR on core, pulling the types out into a separate file there and adding your new types?

I was literally thinking `markup`. Or maybe `webpage`.

**Comment by nagem** [comment]
@gsfr I hadn't heard of that plan, but I agree with it.

**Comment by gsfr** [comment]
Plan is such a strong word... https://github.com/scitran/core/pull/323#issuecomment-221442603

**Comment by lmperry** [comment]
Closing here. PR on scitran/core/pull/345

**Pull request closed without merging**
