### PR TITLE
ENH: MEEG file reaping

### PR DESCRIPTION
**Pull request by larsoner**
Start of MEEG file reaping.

related to https://github.com/scitran/data/pull/28

### CODE REVIEW

**Comment by larsoner** [comment]
So far I have a clean/new `scitran` instance running on my machine with `./live.sh run`. I also have the reaper from this PR running with:

```
./meeg_file_reaper.py -s 1 -u http://localhost:9001/scitran ~/Desktop/test/
```

And the output is:

```
2015-08-12 11:12:24      reaper.meeg:INFO Monitoring acquisition directory /home/larsoner/Desktop/test/
2015-08-12 11:12:24           reaper:INFO initializing MEEGFileReaper...
2015-08-12 11:12:24           reaper:INFO loaded       1 items from persistence file, 1 not reaped
2015-08-12 11:12:24           reaper:INFO monitoring   /home/larsoner/Desktop/test/eric_non_space/maddox_ross/20150810 [2015-08-10 15:09:25, 1 files, 38M]
2015-08-12 11:12:24           reaper:INFO monitoring   1 items, 1 not reaped
2015-08-12 11:12:25           reaper:INFO reap queue   item 1 of 1
2015-08-12 11:12:25      reaper.meeg:INFO reaping      /home/larsoner/Desktop/test/eric_non_space/maddox_ross/20150810 [2015-08-10 15:09:25, 1 files, 38M]
2015-08-12 11:12:25      reaper.meeg:INFO reaped       /home/larsoner/Desktop/test/eric_non_space/maddox_ross/20150810 (1 images) in 0.3s
2015-08-12 11:12:25      reaper.meeg:INFO compressing  /home/larsoner/Desktop/test/eric_non_space/maddox_ross/20150810
2015-08-12 11:12:29           reaper:INFO hashing      reap.tgz
2015-08-12 11:12:29           reaper:INFO uploading    reap.tgz [27M] to http://localhost:9001/scitran
2015-08-12 11:12:29           reaper:ERRO error        reap.tgz: ('Connection aborted.', error(32, 'Broken pipe'))
```

I suspect I have a badly formatted URI, but what should it be? I tried `https` but I got an un-caught error:

```
...
2015-08-12 11:26:55           reaper:INFO uploading    reap.tgz [27M] to https://localhost:9001/scitran
Traceback (most recent call last):
  File "./meeg_file_reaper.py", line 124, in <module>
    main()
  File "./meeg_file_reaper.py", line 120, in main
    reaper.main(MEEGFileReaper, positional_args, optional_args)
  File "/home/larsoner/python/scitran/code/reaper/scitran/reaper/reaper.py", line 324, in main
    reaper.run()
  File "/home/larsoner/python/scitran/code/reaper/scitran/reaper/reaper.py", line 190, in run
    if self.upload(tempdir):
  File "/home/larsoner/python/scitran/code/reaper/scitran/reaper/reaper.py", line 252, in upload
    success = self.http_upload(filename, filepath, digest, uri)
  File "/home/larsoner/python/scitran/code/reaper/scitran/reaper/reaper.py", line 275, in http_upload
    r = requests.put(uri, data=fd, headers=headers)
  File "/home/larsoner/.local/lib/python2.7/site-packages/requests/api.py", line 110, in put
    return request('put', url, data=data, **kwargs)
  File "/home/larsoner/.local/lib/python2.7/site-packages/requests/api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/home/larsoner/.local/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/larsoner/.local/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/home/larsoner/.local/lib/python2.7/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/home/larsoner/.local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/home/larsoner/.local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 344, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/home/larsoner/.local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 314, in _raise_timeout
    if 'timed out' in str(err) or 'did not complete (read)' in str(err):  # Python 2.6
TypeError: __str__ returned non-string (type SysCallError)
```

Is this documented somewhere? I'm starting to add it to `README.md` in this PR.

Also, what is the suggested folder structure for development? Should this `reaper` repo be checked out into the folder from the `scitran` repo `scitran/code/`?

**Comment by gsfr** [comment]
The API has a `POST /reaper` endpoint. This should be, but isn't, documented in the API.

When running with `live.sh`, I believe that the API by default runs on `https`, port 8443. You will also need to provide the newly-introduced shared secret in the URL, matching that in your `scitran/scitran/config.toml`.

So, your upload URL should be something like `https://localhost:8443/api/reaper?secret=change-me`.

We are currently going through a change in the API, converting our on-disk format from .tgz to .zip. You will need to be on the [zipfiles branch](https://github.com/scitran/api/tree/zipfiles) of the API, and I just pushed the matching commits to `reaper:master`.

Since the reaper isn't really part of the core scitran infrastructure, you can put it wherever you want. I typically develop on a separate host, that has access to our MRI instrument.

**Comment by larsoner** [comment]
Great thanks for the quick response, I'll give it a try in the morning.

**Comment by larsoner** [comment]
Rebased, changed the extension to `.zip`, and changed `api` to be on the `zipfiles` branch -- now it seems not to actually do any reaping, although it thinks it did:

```
$ ./reaper/meeg_file_reaper.py -s 1 -u https://localhost:8443/api/reaper?secret=foo persistence ~/Desktop/test/
2015-08-13 10:59:54      reaper.meeg:INFO Monitoring acquisition directory /home/larsoner/Desktop/test/
2015-08-13 10:59:54           reaper:INFO initializing MEEGFileReaper...
2015-08-13 10:59:54           reaper:INFO ignoring     1 items currently on instrument
2015-08-13 10:59:54           reaper:INFO sleeping     1.0s
2015-08-13 10:59:55           reaper:INFO monitoring   1 items, 0 not reaped
```

It doesn't matter what my shared secret is or if I delete the persistence file, it still thinks it has reaped the file and doesn't attempt an upload. Any ideas why this file gets ignored now?

**Comment by larsoner** [comment]
In case you want to reproduce locally, you can:
1. create three levels of directories with an emtpy file with a `.fif` extension, like `~/a/b/c/d.fif`
2. comment out the lines in the "try" part of `meeg_file_reaper.py` around line 80, where it checks to make sure we have the right type of file (`import mne` through `allow_maxshield=True)`).
3. run the standard reaping command like `./reaper/meeg_file_reaper.py -s 1 -u https://localhost:8443/api/reaper?secret=foo persistence ~/a`

**Comment by larsoner** [comment]
I just tried re-running the reaper, and for some reason I now get a little further:

```
2015-08-13 15:32:04      reaper.meeg:INFO Monitoring acquisition directory /home/larsoner/Desktop/test/
2015-08-13 15:32:04           reaper:INFO initializing MEEGFileReaper...
2015-08-13 15:32:04           reaper:INFO loaded       1 items from persistence file, 1 not reaped
2015-08-13 15:32:04           reaper:INFO monitoring   /home/larsoner/Desktop/test/eric_non_space/maddox_ross/20150810 [2015-08-10 15:09:25, 1 files, 38MB]
2015-08-13 15:32:04           reaper:INFO monitoring   1 items, 1 not reaped
2015-08-13 15:32:05           reaper:INFO reap queue   item 1 of 1
2015-08-13 15:32:05      reaper.meeg:INFO reaping      /home/larsoner/Desktop/test/eric_non_space/maddox_ross/20150810 [2015-08-10 15:09:25, 1 files, 38MB]
2015-08-13 15:32:06      reaper.meeg:INFO reaped       /home/larsoner/Desktop/test/eric_non_space/maddox_ross/20150810 (1 images) in 0.3s
2015-08-13 15:32:06      reaper.meeg:INFO compressing  /home/larsoner/Desktop/test/eric_non_space/maddox_ross/20150810
2015-08-13 15:32:10           reaper:INFO hashing      reap.zip
2015-08-13 15:32:10           reaper:INFO uploading    reap.zip [27MB] to https://localhost:8443/api/reaper?secret=f8bf570aa0fd4406b79c2cb1b59ce666
Traceback (most recent call last):
...
  File "/home/larsoner/python/scitran/code/reaper/scitran/reaper/reaper.py", line 246, in upload
    filename, filepath, digest, uri)
  File "/home/larsoner/python/scitran/code/reaper/scitran/reaper/reaper.py", line 276, in http_upload
    r = requests.post(uri, data=fd, headers=headers)
  File "/home/larsoner/.local/lib/python2.7/site-packages/requests/api.py", line 99, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/larsoner/.local/lib/python2.7/site-packages/requests/api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/home/larsoner/.local/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/larsoner/.local/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/home/larsoner/.local/lib/python2.7/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/home/larsoner/.local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/home/larsoner/.local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 344, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/home/larsoner/.local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 314, in _raise_timeout
    if 'timed out' in str(err) or 'did not complete (read)' in str(err):  # Python 2.6
TypeError: __str__ returned non-string (type Error)
>>> import pdb; pdb.pm()
> /home/larsoner/.local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py(314)_raise_timeout()
-> if 'timed out' in str(err) or 'did not complete (read)' in str(err):  # Python 2.6
(Pdb) p err
SSLError('bad handshake', Error([('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')],))
(Pdb) 
```

So it looks like I have a certificate problem. Is this expected? I was kind of hoping this would more or less work out of the box for development without needing to set up certificates. Is it supposed to?

**Comment by larsoner** [comment]
...and a little bit further, with `requests.post(..., verify=False)`:

```
2015-08-13 15:37:12           reaper:INFO uploading    reap.zip [27MB] to https://localhost:8443/api/reaper?secret=f8bf570aa0fd4406b79c2cb1b59ce666
/home/larsoner/.local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
2015-08-13 15:37:12           reaper:WARN failure      reap.zip: 502 Bad Gateway
```

**Comment by larsoner** [comment]
The relevant `nginx-access.log`:

```
127.0.0.1 - - [13/Aug/2015:15:44:41 -0400] "POST /api/reaper HTTP/1.1" 502 172 "-" "SciTran Drone reaper home_larsoner_Desktop_test"
```

`nginx-error.log`:

```
2015/08/13 15:44:41 [error] 20528#0: *1 writev() failed (104: Connection reset by peer) while sending request to upstream, client: 127.0.0.1, server: , request: "POST /api/reaper HTTP/1.1", upstream: "uwsgi://127.0.0.1:9000", host: "localhost:8443"
```

I don't really know how this stuff works, but I tried setting the `user larsoner;` in `/persistent/generated/nginx/nginx.conf` based on an idea [here](http://stackoverflow.com/questions/23926510/502-bad-gatewaynginx-1-4-7) but that had no effect.

**Comment by larsoner** [comment]
BTW, if someone wants to create the `gitter` room `scitran/scitran` (like [this](https://gitter.im/mne-tools/mne-python)) that could be a great place to discuss this interactively at some point. I'd create the room, but I think it needs to be done by someone with ownership.

In the meantime, sorry for the spam-quantity responses/notifications -- I keep thinking I've hit a dead end where I need help, but I keep getting tiny bits further. Hopefully it at least gives some insight into the new-developer process :)

**Comment by gsfr** [comment]
I'm sorry, but I won't be able to get onto gitter. I'm totally swamped as it is.

Thanks for adding the `insecure` option.

@kofalt Any ideas on that nginx error above?

**Comment by larsoner** [comment]
Perhaps some more hints from `uwsgi.log`, it looks like some inexplicable `numpy` import error:

```
*** Starting uWSGI 2.0.11 (64bit) on [Fri Aug 14 13:22:44 2015] ***
compiled with version: 4.9.2 on 13 August 2015 16:11:25
os: Linux-3.19.0-25-generic #26-Ubuntu SMP Fri Jul 24 21:17:31 UTC 2015
nodename: bunk.ilabs.washington.edu
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 12
current working directory: /home/larsoner/python/scitran
writing pidfile to persistent/pids/uwsgi.pid
detected binary path: /home/larsoner/python/scitran/persistent/venv/bin/uwsgi
chdir() to code/api
your processes number limit is 96282
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP6 address [::]:9000 fd 7
Python version: 2.7.9 (default, Apr  2 2015, 15:37:21)  [GCC 4.9.2]
Python main interpreter initialized at 0x220cfd0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 415360 bytes (405 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
added code/data/ to pythonpath.
Traceback (most recent call last):
  File "api.wsgi", line 15, in <module>
    import api
  File "./api.py", line 10, in <module>
    import projects
  File "./projects.py", line 9, in <module>
    import scitran.data.medimg
  File "/home/larsoner/python/scitran/code/data/scitran/data/medimg/__init__.py", line 29, in <module>
    from . import medimg
  File "/home/larsoner/python/scitran/code/data/scitran/data/medimg/medimg.py", line 23, in <module>
    import dcmstack
  File "/home/larsoner/python/scitran/persistent/venv/local/lib/python2.7/site-packages/dcmstack/__init__.py", line 7, in <module>
    from .dcmstack import *
  File "/home/larsoner/python/scitran/persistent/venv/local/lib/python2.7/site-packages/dcmstack/dcmstack.py", line 7, in <module>
    import nibabel as nb
  File "/home/larsoner/python/scitran/persistent/venv/local/lib/python2.7/site-packages/nibabel/__init__.py", line 38, in <module>
    from . import analyze as ana
  File "/home/larsoner/python/scitran/persistent/venv/local/lib/python2.7/site-packages/nibabel/analyze.py", line 85, in <module>
    import numpy as np
  File "/home/larsoner/python/scitran/persistent/venv/local/lib/python2.7/site-packages/numpy/__init__.py", line 170, in <module>
    from . import add_newdocs
  File "/home/larsoner/python/scitran/persistent/venv/local/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/home/larsoner/python/scitran/persistent/venv/local/lib/python2.7/site-packages/numpy/lib/__init__.py", line 17, in <module>
    from . import scimath as emath
ImportError: cannot import name scimath
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 9410)
spawned uWSGI worker 1 (pid: 9434, cores: 2)
spawned uWSGI worker 2 (pid: 9435, cores: 2)
spawned uWSGI worker 3 (pid: 9436, cores: 2)
spawned uWSGI worker 4 (pid: 9437, cores: 2)
--- no python application found, check your startup logs for errors ---
[pid: 9435|app: -1|req: -1/1] 127.0.0.1 () {44 vars in 698 bytes} [Fri Aug 14 13:25:24 2015] POST /api/reaper => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 9435|app: -1|req: -1/2] 127.0.0.1 () {44 vars in 698 bytes} [Fri Aug 14 13:25:28 2015] POST /api/reaper => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 1)
--- no python application found, check your startup logs for errors ---
[pid: 9437|app: -1|req: -1/3] 127.0.0.1 () {44 vars in 698 bytes} [Fri Aug 14 13:27:39 2015] POST /api/reaper => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
```

The bottom three lines correspond to three attempts to upload some data using the reaper. I tried starting from a fresh `scitran` and going through the `setup`, `configure`, `run` steps, and this is the behavior I got.

**Comment by larsoner** [comment]
Alright, I found it! I have an older `libgfortran.so` on my system for compatibility with some old software, and somehow the `numpy` build was linking to that, and when doing `import numpy` that bit would fail. Moving my `libgfortran.so` so that it isn't used got me to:

```
2015-08-14 14:15:03           reaper:INFO hashing      reap.zip
2015-08-14 14:15:03           reaper:INFO uploading    reap.zip [27MB] to https://localhost:8443/api/reaper?secret=c2a9109b031f43f484c8958190b16715
/home/larsoner/.local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
2015-08-14 14:15:03           reaper:INFO uploaded     reap.zip [182MB/s]
2015-08-14 14:15:03           reaper:INFO monitoring   1 items, 0 not reaped
```

So that's some progress!

**Comment by kofalt** [comment]
@Eric89GXL I'm not very familiar with how various `.so` files get linked (or not) by python, how was that happening and does a venv fix / affect the problem?

**Comment by kofalt** [comment]
Am I correct in thinking it's now working for you? That log looks good...

**Comment by larsoner** [comment]
Yeah, the reaper now appears to work / upload data, and it's the parser that I'm getting errors on. But I'm slowly progressing through them. First I had to rebase my `data/meeg` branch on the `zip_parse` branch. Now I actually need to make the `MEEGReader` work better.

**Comment by larsoner** [comment]
Okay, I think this one is ready. It successfully uploads to the `scitran` instance / `data` parser.

**Comment by gsfr** [comment]
Thanks, @Eric89GXL.
What's the purpose of your modifications of `reaper.py`?
I see the need for the `insecure` option, but I'm not sure I like/understand the rest.

**Comment by larsoner** [comment]
Currently (on `master`) if you give a badly formatted URI as an argument to your reaper, you don't find out that the URI is no good until the reaper actually tries to complete an upload. This is not as nice as being notified immediately when you fire up the reaper. To parse the URI at startup, it's good to use the same logic that will be used later, which is why the URI parsing was moved to a separate function (DRY). Make sense?

**Comment by gsfr** [comment]
Yup, makes sense. I will review more closely on Monday.

**Comment by gsfr** [comment]
This is mostly good, bar one issue and some styling changes I'd like to apply. For me, 80 char lines really reduce readability on modern displays, for instance. Let me know the best way to apply my changes. I'd be happy to do so after merging.

The issue is that the bad URL `RuntimeError` is never actually raised. I guess that's not what you intended.

**Comment by larsoner** [comment]
Ahh yes, I can fix the non-error-raising and push.

Regarding the 80-char limits, I do it mostly to follow standard Python / PEP8 style, but I also think the current code is pretty readable as is. You're welcome to change the spacing yourself after merging, but it might be better long-term if you point out your preferences e.g. in this PR so I can change them instead. That way I can conform to your development preferences in other future PRs and you won't have to play cleanup after merging all the time.

**Comment by larsoner** [comment]
Or if it's faster for you just to merge now that I've fixed the `raise` issue and commit to `master` afterward, just let me know when it's in and I'll take a look at what you did. That might be easier.

**Comment by gsfr** [comment]
I just added one more commit to master: 83366aa35768934e870579be36048dca5fa0f50b

We basically try to follow PEP8, minus fairly obvious stuff like line length. Also, this code has all existing prints starting with lowercase, so I harmonized that too.

I'd love to be more rigorous and force the use a linter.

**Comment by larsoner** [comment]
I've set that up on Travis for multiple repos, I can add one for this or
other repos tomorrow if you want. Just need to decide which PEPs to omit if
there are any beyond line length. We can look at the Travis complaints once
implemented if that works for you.

**Comment by gsfr** [comment]
Sure, that works. We also need to be able to do it locally, though. I'm thinking something like `pylint`.

**Comment by kofalt** [comment]
I've got pylint already rigged for the API: https://github.com/scitran/scitran/blob/035c66ebe93c48345482b407f6741e0af2b30e4a/scripts/2-run.sh#L157-L186

It's not in use though, need someone to decide which flags we're using, make the codebase compliant with said choices, and add the check to the CI target. Not sure if a ticket should be filed on sc/sc, sc/api, or both :)

Maybe something to prioritize scitran/scitran#2 for, since there's an increasing number of split-brain things I'd like to do to this codebase. Alternatively, CI could simply clone sc/sc.

**Comment by larsoner** [comment]
I usually use flake8, any idea if one is better than the other?

**Comment by kofalt** [comment]
Not a clue, but I was very impressed by pylint's speed, sensible output, and level of sophistication.

**Pull request merged**
