### PR TITLE
Dicom folder sniper

### PR DESCRIPTION
**Pull request by gsfr**
The primary purpose of this PR is to add the DICOM folder sniper. This new code has been reviewed and tested by @lmperry and does not require further detailed review.

Logging for all tools was also adapted and should be reviewed carefully.

All tools are now generally expected to run at the new default log level, *warning*. The *info* level should be slightly more chatty, and the *debug* level should be reserved for actual debugging activities.

The user-facing *snipers* use a different log format than the automated *reapers*. Tools can now control their own log format more easily.

*Anonymization* terminology was partially changed to a more accurate *de-identification*. That change should be propagated throughout the code before merging this PR.

I further propose that de-identification not be turned on by default. Handled data should not be manipulated in any way without the user's explicit consent. @ryansanford @lmperry Thoughts?

### CODE REVIEW

**Comment by ambrussimon** [comment]
Thanks for the heads up. Rebased EEG reaper locally, and needed to resolve only one minor conflict, after which everything works A-OK :+1:

**Review by ambrussimon — APPROVED** [review]

**Comment by lmperry** [comment]
LGTM. I agree with we should not modify/delete fields within the DICOMs without specific direction by the user.

**Comment by gsfr** [comment]
@lmperry @ambrussimon-invenshure I added two more small commits to follow up on de-identification. This PR is now good to go from my end. Will merge tomorrow, unless I'm advised otherwise.

**Comment by lmperry** [comment]
LGTM

**Pull request merged**
