### PR TITLE
Perf log

### PR DESCRIPTION
**Pull request by gsfr**
Add a bunch of performance related logging to dicom sniper and reaper. No functional changes.

### CODE REVIEW

**Comment by gsfr** [comment]
@ryansanford Could you please take a look? I'd like to land this soon so that we get better performance insights in the field.

Also, separately from this, we seem to have issues with Travis intermittently exceeding its maximum allowed time. I had to restart this build several times in order to get it to complete. Possibly, Travis was under higher than normal load. Anyway, CI is always taking a long time and we should try to cut it back. Also, the log verbosity is overly high.

**Comment by ryansanford** [comment]
@gsfr I'll test this first thing tomorrow.

**Comment by ryansanford** [comment]
@gsfr My comments...
- The `Reaping` `Inspecting` `Compressing` `uploading` events should be moved to Debug level.
- `uploading` should be capitalized
- `success` message should be renamed to `Uploaded`
- Timing should be captured in the state file. I lean more towards raw timestamps, and let state file analysis scripts do the interpretation. I think there's value in the PR without this last item, but it should be a fast follow, as we can't always rely on the presence of these logs.

**Comment by gsfr** [comment]
Thanks, @ryansanford. First three bullets done, but I kept `Reaping`/`Fetching` in `info` level. Otherwise there are potentially long periods of no information.

Last bullet should be a separate, non-reactive, effort. Let's spend some time on Thursday on this.

**Comment by ryansanford** [comment]
Changes LGTM. I'll create a ticket for the last bullet for tracking our conversation.

**Pull request merged**
